# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: 
  pull_request:
    branches: 
      - master
      - develop
      - feature/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.1.0
    - run: yarn lint
    - run: yarn lint-fix
      env:
        CI: true
